export * from "./envelope";
export * from "./lock";
export * from "./eye";
export * from "./facebook";
export * from "./google";
export * from "./profile";
export * from "./home_icon";
export * from "./booking_icon";
export * from "./calendar";
export * from "./inbox";
export * from "./person";
export * from "./person-dark";
export * from "./pencil";
export * from "./nigeria";
export * from "./bookmark";
export * from "./notification";
export * from "./search";
export * from "./evenodd";
export * from "./cleaning";
export * from "./support";
export * from "./concierge";
export * from "./repair";
export * from "./shopping";
export * from "./truck";
export * from "./medal";
export * from "./bookmarked";
export * from "./menu";
export * from "./love-outlined";
export * from "./love-solid";
export * from "./phone";
export * from "./menu-icon";
export * from "./minus";
export * from "./plus-icon";
export * from "./location-icon";
export * from './paypal'
export * from './paystack'
export * from './qr-image'
export * from './copy'
export * from './download'
export * from './share'
export * from './print'